Teleopti/styleguide

css/_list.scss
=> Let's have nice lists with cards

css/_icons.scss
=> add mdi-chart-line example

css/_icons.scss
=> replace the chart icon

app.js, css/_cardlist.scss, css/main.scss, kss-template/index.html, vendor/cardlist/teleopticardlist.directive.js
introduce card list directive on the section 2.4 which it may be used by
others
=> teleopti card list

app.js, css/_cardlist.scss, css/main.scss, kss-template/index.html, vendor/cardlist/teleopticardlist.directive.js, vendor/wfmDirectives/cardlist/wfmcardlist.directive.js
wfm card list, with tidy up changes according Blandine suggestions
=> Wfm card list

app.js, css/_cardlist.scss, vendor/wfmDirectives/cardlist/wfmcardlist.directive.js
update card list directives to support multi selecting
=> wfm card list update

app.js, css/_pagination.scss, kss-template/index.html, vendor/wfmDirectives/pagination/wfmpagination.directive.js
Hi Carl,
Please check if anything inappropriate or missing.
Thanks.
Chundan
=> add wfm pagination directive

css/_form.scss, css/_loading.scss, css/_tabs.scss, css/styleguide.css, package.json
=> upgrade angular-material version from 0.10.1 to 0.11.4

.travis.yml, deploy-package.sh
=> added npm publish step

deploy-package.sh
minor fix to enable npm publish
=> Added login details

.travis.yml, deploy-package.sh, package.json
=> changed deploymed policy

directives/date-range-picker/date-range-picker.directive.js, directives/date-range-picker/date-range-picker.tpl.html
so that the initial values are displayed correctly.
=> Fix missing render.

.travis.yml, package.json
new version with working directives
=> bump version to 1.1.3

package.json
include numeric value directive
=> v.1.1.4-beta.3

.gitignore, Gruntfile.js, css/_classicvariables.scss, css/_colors.scss, css/_darkvariables.scss, css/main_dark.scss, css/styleguide.scss
styleguide part of enableing darktheme, we mirror this in main project
=> inital commit to enable dark theme

directives/time-range-picker/time-range-picker.directive.spec.js
This PR fixes an issue with Jasmine 2.x, where promises are not resolved. Thanks @stephenwan
=> Fix timeout fails in tests

directives/time-range-picker/time-range-picker.directive.spec.js
This PR just restores dependency injection as before.
=> Restore dep injection

.jshintrc, css/form_panel.hbs, css/styleguide.scss, directives/autofocus/wfmautofocus.directive.js, directives/autofocus/wfmautofocus.directive.spec.js
Tested in the project and it works
=> wfm-autofocus

css/_form.scss, css/form_panel.hbs, css/styleguide.scss
made the md-select example work (as per bug #38485) and removed the standard select example and   in form to fase it out
=> Fix md select 

app.js, directives/notice/notice.directive.js
http://challenger:8080/tfs/web/UI/Pages/WorkItems/WorkItemEdit.aspx?id=38869
=> Clear notices on dbl click

css/_material.scss
=> removed media query

css/_form.scss
Make our checkbox "focusable" so that the user can check/uncheck via keyboard.
=> Focusable checkbox

directives/pagination/wfmpagination.directive.js, directives/pagination/wfmpagination.directive.spec.js
Add pageIndex range validation
=> Add pageIndex range validation

app.js, css/_datepicker.scss, css/dateRangePicker.hbs, directives/date-range-picker/date-range-picker.directive.js, directives/date-range-picker/date-range-picker.tpl.html, kss-template/index.html
Trying to address #97 and #98 from Rob.
=> Date range picker improvement

css/_cards.scss
Better grid that use 100% of the width (in the project. styleguide example is skewed for some reason).
The old grid is still there to be able to depreciate it over time.
=> refactor card grids

css/_cards.scss, directives/cardlist/wfmcardlist.directive.js
possibility to open card list correctly with tab
=> focusable card list

css/_buttons.scss, css/_form.scss, css/styleguide.md, css/styleguide.scss
Better descriptions and fixed typos
=> descriptions

css/_notices.scss
cange color of the error notice to be more readable in dark theme
=> notice color

css/_form.scss, css/form_panel.hbs
fixes https://github.com/Teleopti/styleguide/issues/58
=> fix autocomplete in forms

css/_datepicker.scss, directives/date-range-picker/date-range-picker.directive.js, directives/date-range-picker/date-range-picker.directive.spec.js, directives/date-range-picker/date-range-picker.tpl.html, directives/time-range-picker/time-range-picker.directive.js, kss-template/index.html, package.json, vendor/ui-bootstrap-custom-build/datepicker.directive.ext.js, vendor/ui-bootstrap-custom-build/timepicker.directive.ext.js
Bump angular-ui-bootstrap from 0.14.x to ^2.1.3.
Fixed the compatibility issues and cleaned up the dirty hacks used before.
=> Upgrade ui bootstrap from 0.14.x to 2.1.3

Gruntfile.js, css/_colors.scss, css/_darkvariables.scss, css/_notices.scss, css/styleguide.scss
=> modified red values in dark theme and adjusted notice error

Gruntfile.js
=> added continuous grunt karma task

css/_workinghourspicker.scss, directives/workinghourspicker/working-hours-picker.directive.js
=> expose the disableNextDay option in working-hours-picker

css/_timepicker.scss, directives/time-range-picker/time-range-picker.tpl.html, directives/workinghourspicker/working-hours-picker.tpl.html
A suggestion to make the time-range-picker and the working-hours picker more similar
=> Response to #135

css/_form.scss
The thumb handle was missing when using the labeled slider, also added a vertical slider
=> vertical slider and fixed thumb 

css/form_panel.hbs, css/styleguide.scss
The old form layout relied on dl and dd tags for layout and the example was broken.
now it uses the flex grid layout, this also provides better ability to have two inputs on the same line
=> Form layout

css/_form.scss
this input will not wrap as the old one did, instead it will be housed inside a con-flex and be 100% width
=> input prepend

app.js, directives/wfm-right-panel/wfm-right-panel.directive.js, directives/wfm-right-panel/wfm-right-panel.tpl.html
move wfm.rightPanel folder from project to here
=> add wfm.rightPanel

css/_datepicker.scss, directives/date-range-picker/date-range-picker.directive.spec.js, directives/date-range-picker/date-range-picker.tpl.html
changed template for popup datepicker. inline datepicker is wrapped and displayed on click.
=> popup datepicker in directive

css/_chips.scss, css/_form.scss, css/_helpers.scss, css/_timepicker.scss, css/_workinghourspicker.scss
moved some style that should be in the styleguide rather than the project
=> moved temp style from the project

css/_tables.scss
minor color change for tables in dark theme
=> table color

Gruntfile.js
http://26.media.tumblr.com/tumblr_lm9y55ivt91qg385jo1_500.jpg
=> This hurts the deployment

css/_timepicker.scss
allow the labels to have any length of text inside them
=> time range picker labels

Gruntfile.js, kss-template/index.html
=> Patch for styleguide gh-page

css/chips.hbs
=> make chips wrap on small screens

css/_buttons.scss, css/_form.scss, css/_icons.scss, css/styleguide.scss
*added icon button example
*refreshed icon index
*changed descriptions to make (more) sense
*made internal links work correctly
=> Refresh icons and descriptions

css/_form.scss
i dont really know why but the checkbox was only transparent and not hidden
=> remove real checkbox

css/_datepicker.scss, css/_tables.scss
Ui-grid and uib-datepicker doesnt use mdi icons so when the lib was updated the workaround we used broke. Replaced the workaround with text symbols and css 
Issue marked with red
Changes marked with dark blue
=> fix non mdi icons

css/_form.scss
minor fix to remove the italic inherited from the i tag
=> dont slant input text

css/_tables.scss, package.json
quick fix that needs release to fix the icons in the ui grid
=> Fix grid icons again

directives/cardlist/wfmcardlist.directive.js
=> Create child scope in card list directive

css/form2_panel.hbs, css/form3_panel.hbs, css/form_panel.hbs, css/styleguide.scss
https://github.com/Teleopti/styleguide/issues/205
split the for example over 3 different examples to show of configurations in a neater way
=> Add some more form templates

.vscode/settings.json, css/_icons.scss, directives/wfm-right-panel/wfm-right-panel.tpl.html
changed icons for open/close right panel
=> changed icons for open/close right panel

css/_datepicker.scss, css/_form.scss, css/_list.scss, css/_material.scss, css/_menus.scss, css/_modal.scss, css/_navbar.scss, css/_timepicker.scss, css/_tooltip.scss
This is to fix https://github.com/Teleopti/styleguide/issues/215
i think its time we lower the overall z index level and bring back some order:
Step one, make this PR work in the product (this might take some work)
Step two, define 'layers' and try to fit elements on them (to avoid raising the level again), maybe providing variables
=> lower all z-index

css/_form.scss
when this is released i will remove the temp styles in the project
=> moved temp style from _layout.scss

css/styleguide.scss
some info about how to keep the z-index lower
=> z index section

css/_cards.scss, css/_datepicker.scss, css/_form.scss, css/_helpers.scss, css/_material.scss, css/_navbar.scss, css/_tree.scss, css/_workinghourspicker.scss
IE10 cant handle flex all that well - there will be a related bug on the board.
This pr adds fallback for IE10 as shown here:
https://css-tricks.com/using-flexbox/
=> IE10 support for flex

css/chips_filter.hbs
The chips filter was not using the new full width input prepend and was therefore not responsive
=> update chip filter input

css/styleguide.scss
Indicate what font color should be used on each and every color we use.
Confirmed with google material design colors as far as possible (since we have some custom colors, these were approximated) 
https://material.io/guidelines/style/color.html#color-color-palette
=> align text with colors

css/_cards.scss, css/_helpers.scss, css/_workinghourspicker.scss
- moved some style from the project
- fixed https://github.com/Teleopti/styleguide/issues/237
=> move style

Gruntfile.js, directives/wfm-multiple-search/wfm-multiple-search-input.directive.js, directives/wfm-multiple-search/wfm-multiple-search-input.directive.spec.js, directives/wfm-multiple-search/wfm-multiple-search-input.tpl.html
bug #42732 make all place holders in advanced search consistent with field name in person finder in fat client.
bug #44390 the format for keyword doesn't work and the generated expression from advanced search should be equivalent to direct input with the same expression in simple search.
=> Bug42732and44390

css/_buttons.scss, css/_menus.scss, css/_notices.scss
- Give the ability to set colors to the icon button (context menu trigger).
- Removed the mini fabs so that we can work on https://github.com/Teleopti/styleguide/issues/242 without messing with them.
Before starting that one we need to clear the project of mini buttons and replace them with icon buttons.
- Changed the focus state of the icon button to be less annoying.
- Add example of a disabled icon button
=> Icon button background

directives/date-range-picker/date-range-picker.directive.js, directives/date-range-picker/date-range-picker.tpl.html
so that the component can display in different languages
=> enable to pass translations of label texts

css/_animation.scss, css/_notices.scss, css/start.html, css/styleguide.scss
a section in the styleguide with a guide explaining how to go about building a view and a quick-copy example of the basic layout structure 
This will help speed up the process of starting a view and serve as a small checklist to build the right thing.
i think the text might need some proofreading by someone who isnt as in-depth in the styleguide to make sure its understandable.
later we might also add a "do/dont" section to this chapter
=> get started

css/_buttons.scss, css/_darkvariables.scss
colors were hard coded and there were a lot of !important confusion
=> dark theme button colors

css/_workinghourspicker.scss, directives/work-hour-picker/work-hour-picker.component.js, directives/work-hour-picker/work-hour-picker.component.spec.js, directives/work-hour-picker/work-hour-picker.tpl.html, js/app.js, package.json
fix https://github.com/Teleopti/styleguide/issues/227
translation keys are obviously missing the translations
=> work hour picker 2

directives/badge/badge.tpl.html, directives/badge/wfm-badge.component.js
break out template to html file
=> badge template

css/styleguide.scss
last step of the wizard panel should not tell the user to go to the (nonexistent) next page
=> control the wizard

css/_form.scss, directives/wfm-multiple-search/wfm-multiple-search-input.directive.js, directives/wfm-multiple-search/wfm-multiple-search-input.tpl.html
Add keyboard control for multiple search input
=> Add keyboard control for multiple search input

css/_form.scss, directives/wfm-multiple-search/wfm-multiple-search-input.directive.js, directives/wfm-multiple-search/wfm-multiple-search-input.tpl.html
Reverts Teleopti/styleguide#265
=> Revert "Add keyboard control for multiple search input"

css/_form.scss, directives/wfm-multiple-search/wfm-multiple-search-input.directive.js, directives/wfm-multiple-search/wfm-multiple-search-input.tpl.html
=> Add keyboard control

.travis.yml, deploy-ghpages.sh
dont clear up changes by depolyment
=> dont clear up changes by depolyment

directives/wfm-helping-directives/wfm-helping-directives.js, directives/wfm-multiple-search/wfm-multiple-search-input.directive.js, directives/wfm-multiple-search/wfm-multiple-search-input.tpl.html
fixed multiple search input popup issue
=> fixed multiple search input popup issue

directives/wfm-helping-directives/wfm-helping-directives.js, directives/wfm-multiple-search/wfm-multiple-search-input.directive.js, directives/wfm-multiple-search/wfm-multiple-search-input.directive.spec.js, directives/wfm-multiple-search/wfm-multiple-search-input.tpl.html
Add Esc to close advance search and some enhancement.
=> Add Esc to close advance search and some enhancement.

css/_form.scss, directives/wfm-multiple-search/wfm-multiple-search-input.directive.js
=> delete outline when unfoucsed

css/_form.scss
fix bug: No selected mark when I use keyboard to focus on search icon
=> fix bug: No selected mark when I use keyboard to focus on search icon

css/_form.scss
radio buttons and switches dont work on chrome mobile browser, will start by removing anything apart from standard css and see if that helps
=> remove split support for browsers

css/_form.scss
will try to undo https://github.com/Teleopti/styleguide/commit/7551062376aeec229a5f42f2542fafae9ac5fd8f
to make it work on mobile browsers again
=> put back checkbox in switch

css/_list.scss
Reminder: remove the quick fix in _layout.scss after merge and release
=> list dot fix

package.json
Changeset 57992 (007624800cb7) Update ui-grid to fix bug #45601: Requests:It doesn't clear selection on agents when switching between business Hierarchy and group pages
=> Update ui-grid to v3.2.9

app.js, css/_cards.scss, css/cardlist_default.hbs, directives/cardlist/wfmcardlist.directive.js
Should give an option for https://github.com/Teleopti/styleguide/issues/239
=> card-control

css/_form.scss, css/_material.scss, directives/skill-picker/skill-picker.tpl.html, directives/skill-picker/skill.picker.component.js, directives/skill-picker/skill.picker.component.spec.js, js/app.js
Show the skill-picker component in the styleguide, shoud be useful in several modules
=> skill picker

js/app.js
=> add another

README.md, css/_typo.scss, js/app.js, kss-template/index.html
- search functionality
- header icon goes to the startpage
=> start page with search

css/_datepicker.scss, css/_timepicker.scss, js/app.js, kss-template/index.html
=> cleanup before release

directives/notice/notice.directive.spec.js, directives/notice/notice.service.js
As per request, this prevents the notice service from triggering the same notice over and over again
=> remove duplicated notices

css/_buttons.scss, js/app.js
=> icon button loading state

css/_datepicker.scss, css/_form.scss, css/form2_panel.hbs, css/form3_panel.hbs
Use md-checkbox, md-switch and md-radiobutton instead
=> Remove checkbox radio and switch hack

css/_buttons.scss, css/_cards.scss, css/_chips.scss, css/_form.scss, css/_list.scss, css/_loading.scss, css/_menus.scss, css/_modal.scss, css/_navbar.scss, css/_notifications.scss, css/_rightpanel.scss, css/_tables.scss, css/_tooltip.scss, css/_typo.scss, css/styleguide.scss
Removed all subchapters
this will make every section show up in the search and in the sidebar
Renamed some chapters 
- singular form
- details in parentheses so it shows up as related in searches
=> change chapters

css/_helpers.scss
added two classes for aligning items vertically in a con-row
=> vertical alignment helpers

css/chips_filter.hbs, js/app.js
resolve console errors about translation sanitization strategy and non-unique naming
=> remove console errors

css/styleguide.scss, js/app.js, kss-template/index.html
- move the list of resources to js to save space and make it easy to keep it up-to-date
- added categories to resource links so they can be grouped
=> resource section changes

css/_buttons.scss, css/_colors.scss, css/_darkvariables.scss, css/_form.scss, css/_list.scss, css/_menus.scss, css/_tables.scss, css/styleguide.scss
- explain the new color system in "Color shorthand" chapter
- will release a test version asap
=> colors part 3

directives/popup-menu/popup.tpl.html, package-lock.json
There seems to be an extra </div> in the popup-menu template that shouldn't be there
=> Extraneous </div> found in popup-menu

css/_typo.scss
Explain how to foramt translations and how to use jalaali filter
=> translation desc

css/_tree.scss, css/_typo.scss, directives/tree-picker/tree.component.js, directives/tree-picker/tree.component.pickerfilter.spec.js, directives/tree-picker/tree_data.tpl.html, js/app.js
add tree filter to tree picker
=> add tree filter to tree picker 

css/_tables.scss, css/bigtables.hbs
=> Fix syntax error of big table

css/_form.scss
Commented out a early fix for the height thats obscuring the root cause
=> remove temp fix for clarity

.prettierrc.json, README.md, devserver/index.js, devserver/package-lock.json, devserver/package.json
As a step towards smoother development I added a devserver that serves the files in /styleguide on port 3000 locally. A little bit easier to use when developing.
=> Small devserver added

css/_icons.scss
Looked strange and unclear to have two of the same icon with different definitions
=> move remove icon text

css/_form.scss, css/styleguide.scss, directives/skill-picker-old/skill-picker.old.tpl.html, directives/skill-picker-old/skill.picker.old.component.js, directives/skill-picker-old/skill.picker.old.component.spec.js, js/app.js
Soon to be depricated, but needed for now for backwards compatibility
=> put back the old skill picker for now

css/_classicvariables.scss, css/_darkvariables.scss, css/_material.scss, package.json
* Don't force body color
* gray012 should actually be 12% black
=> Design fixes

css/_form.scss, css/_icons.scss, css/_list.scss, css/_material.scss, css/_tables.scss, css/_typo.scss
=> It's not important

css/_form.scss, directives/skill-picker/skillPicker.component.js, js/app.js
The items with Id -1 was selectable. Not so anymore.
=> Make "No skill" & "No skillgroup" unclickable

css/_tables.scss, css/_tabs.scss
Made table headers and tab bars a gentle gray instead of a blaring blue.
=> 77511 Table header and tab bar improvement

css/_form.scss, package.json
Checkboxes and radio buttons now look more like regular checkboxes and radio buttons.
=> 77512 Improve radio buttons and checkboxes

README.md, css/_form.scss, css/_tables.scss, css/_tree.scss, package.json
I found two more types of checkboxes...
=> Made more checkboxes better

.prettierrc.json, directives/calendar-picker/_moudules.js, directives/calendar-picker/calendar-picker.basic.spec.js, directives/calendar-picker/calendar-picker.custom.spec.js, directives/calendar-picker/calendar-picker.gregorian.template.tpl.html, directives/calendar-picker/calendar-picker.jalaali.template.tpl.html, directives/calendar-picker/calendar-picker.js
Update Prettier settings (same with WFM) and format wfm-calendar-picker code based on the new settings
```
{
"printWidth": 120,
"tabWidth": 4,
"singleQuote": true,
"semi": true,
"useTabs": true
}
```
=> Update .prettierrc.json and formatting wfm-calendar-picker

css/_datepicker.scss, directives/wfm-date-picker/wfm-date-picker.gregorian.tpl.html, directives/wfm-date-picker/wfm-date-picker.jalaali.tpl.html, directives/wfm-date-picker/wfm-date-picker.js, directives/wfm-date-picker/wfm-date-picker.spec.js, directives/wfm-date-range-picker/wfm-date-range-picker.basic.spec.js, directives/wfm-date-range-picker/wfm-date-range-picker.gregorian.tpl.html, directives/wfm-date-range-picker/wfm-date-range-picker.jalaali.tpl.html, directives/wfm-date-range-picker/wfm-date-range-picker.js, js/app.js
Now we add popup mode for `wfm-date-range-picker` as well.
=> Add popup mode for wfm-date-range-picker and update usage & doc and refactor

css/_buttons.scss, css/_form.scss
Made inputs, selects, buttons and button groups more in the style of Ant.
=> 77289 fix input style
