css/_list.scss

We may need different widths for wfm-leave-behind depending on the number of buttons to include.
Usage example:
```
<div class="wfm-leave-behind wfm-leave-behind-1">
```
for leave-behind with only 1 button.

More width choices for list-leave-behind.

---

css/_tables.scss

Add a class for "select all" checkbox in ui grid header, refer to bug #34221: When I check all in web people, the box on behalf all is not checked.

Add style for "select all" checkbox in ui-grid header

---

css/_tables.scss

Hi Carl，
This is the strange padding I mentioned in the mail that breaks the ui grid menu style.
Here I just remove it to make the original style from ui grid work.
Please check if there is anything inappropriate.
Chundan

Remove padding for ui grid menu item.

---

.travis.yml

they were broken due to a failed deployment

fix directives in the website

---

directives/time-range-picker/time-range-picker.directive.js
directives/time-range-picker/time-range-picker.directive.spec.js
karma.conf.js
package.json

In this PR, the Time Range Picker will look for locale info from `$locale` rather than `moment` on the global. 
`Angular-i18n` is introduced to provide locale files. And `angular-dynamic-locale` is also imported in testing in order to switch locale.

Use $locale rather than moment to get locale info

---

css/_sidenavs.scss

This PR fixes the issue that the background color of md-sidenav is white in the dark theme.

Specify colors for sidenav in dark theme

---

app.js
directives/workinghourspicker/working-hours-picker.directive.js

Instantiate the initial dates of the component in a standard way compatible with IE and Firefox. The previous format is supported by Chrome only.

Working Hours Picker: invalid date format

---

css/_loading.scss

fix broken spinner by adding color rules. maybe we could update angular material to 1.1.0, in which animation is smoother and theming is simpler.

fix broken spinner

---

directives/date-range-picker/date-range-picker.directive.js

Remove the reduncant declaration for _the start day of week_, because `ui-bootstrap` use `ng-locale` internally.
On the other hand, since in `ng-locale`, 0 is used to stand
for *Monday*, but `ui-bootstrap` is expecting a value with js-standard, i.e. having 0 for *Sunday*, we need to increment the sdow by 1 to make the correct assignment.
[Ref](https://github.com/angular/angular.js/issues/11900)

Let ui-bootstrap use ng-locale on its own.

---

css/_form.scss

keep the green select background on the selected item even if the select is closed and re-opened

keep green selection on select

---

css/_rightpanel.scss
directives/wfm-right-panel/wfm-right-panel.tpl.html

Moved the panel menu class inside the directive template. This might restrict the use of side-panels to be used only inside styleguide panel-containers but i see no issue there since that is the intended use at this point - if other uses are needed later we show examples of them in the styleguide when they appear

Right-panel trigger position

---

css/_material.scss
css/styleguide.scss

The previous layout modification classes were confusing and hard to remember. I added new aliases for these ( 'x2' and 'x3' ) and updated the example to use those so that we can start to phase out the 'split-1-2' and 'split-3-1' naming

Alias for the grid

---

css/_form.scss

Clean up as much custom css as possible to reset the alignment of the select dropdown window so that it matches the input character
dropdown window is semi transparent in this gif to show that the number stays in the same place

Select popup alignment

---

css/_buttons.scss

so that the styles also apply to flat and raised buttons in the "disabled" state.

styles for "disabled" buttons

---

directives/notice/notice.directive.js
directives/pagination/wfmpagination.directive.js

so that our package doesn't affect others during concatenation.

move use strict directives into functions

---

css/_cards.scss
css/_chips.scss
css/_tooltip.scss
css/styleguide.scss
js/app.js

Split the card-grid into two containers:
the fluid layout  - can be used with any element inside it (not just cards) and will wrap the flex items
the card - like a panel but with a more responsive footer that allows for icon buttons as well as text buttons. also it can have background status colors
Tested in the project

separate grid and card

---

css/_menus.scss
directives/popup-menu/popup.component.js
directives/popup-menu/popup.tpl.html
js/app.js

A suggestion for a popup-menu that we can use for different kinds of pickers, toolbar operations and quick selections.
It is a basic transcluded template that allows for whatever we want to use it for
I made the distinction between context menus and popup menus in that context menus contain action lists, popup menus contain anything else. Since the popup menu wont dissapear until clicked outside of there can be small workflows inside it.

popup menu

---

css/_chart.scss
css/_colors.scss
css/_datepicker.scss
css/_form.scss
css/_modal.scss
css/_notices.scss
css/_pagination.scss
css/_rightpanel.scss
css/_tables.scss
css/_tree.scss
css/styleguide.scss
css/tree.hbs
js/app.js
kss-template/index.html

- Update the rest of the styleguide to follow the look of the startpage
- Make it clear where each section start and ends using panels
- Make scroll time shorter by hiding code examples by default
- Better way of declaring and displaying colors for future ease 
- Some typos fixed :)

Refresh styleguide ui

---

css/_animation.scss
css/_buttons.scss
css/_cards.scss
css/_classicvariables.scss
css/_colors.scss
css/_darkvariables.scss
css/_form.scss
css/_helpers.scss
css/_list.scss
css/_material.scss
css/_menus.scss
css/_notices.scss
css/_tables.scss
css/_workinghourspicker.scss
css/styleguide.scss

Change all animations to one standard '$transition-timing' variable apart from 'grow' and 'shrink' that have the double time to indicate where they go.
Also added a section in the helpers about animations

animations

---

css/_helpers.scss

there were 2 .align-row-center helper classes with different align-items declarations

fix wrong class name

---

directives/tree-picker/tree.component.js

The tree filter needs to be reset when the data set changes from parent controller or old filters might be applided resulting in confusing results

reset tree filter when data changes

---

css/_darkvariables.scss

A color should not contain !important suffix

This isn't important #442
